# Generated by Django 5.0 on 2026-02-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cannabis_type',
            field=models.CharField(blank=True, choices=[('flower', 'Flower'), ('pre-roll', 'Pre-roll'), ('vape', 'Vape'), ('edible', 'Edible'), ('concentrate', 'Concentrate'), ('topical', 'Topical'), ('accessory', 'Accessory')], max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='cbd_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='CBD potency (e.g. 0.00)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_cannabis',
            field=models.BooleanField(default=False, help_text='Mark true for cannabis products subject to CA regulations'),
        ),
        migrations.AddField(
            model_name='product',
            name='lab_report',
            field=models.FileField(blank=True, help_text='Upload lab certificate (PDF)', null=True, upload_to='lab_reports/'),
        ),
        migrations.AddField(
            model_name='product',
            name='metrc_tag',
            field=models.CharField(blank=True, help_text='METRC tag / compliance identifier (CA)', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='package_amount',
            field=models.CharField(blank=True, help_text="Quantity/size label (eg '3.5g', '10-pack')", max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_age_verification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thc_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='THC potency (e.g. 18.50)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_weight_g',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weight in grams (for flower) or total package weight', max_digits=8, null=True),
        ),
    ]
